FROM nvcr.io/nvidia/tensorrt:23.08-py3

WORKDIR /app

RUN apt update && apt install ffmpeg libsm6 libxext6 -y && rm -rf /var/lib/apt/lists/*
RUN pip3 install --upgrade pip setuptools wheel

COPY checkpoints/ checkpoints/
COPY requirements.txt ./

RUN pip3 install --no-cache-dir -r requirements.txt
RUN rm -rf /root/.cache
