global:
  precision: fp16
  cuda_devices:
    - "a100"
    - "l40s"
    - "h100"
  s3:
    aws_profile: "apero-software"
    bucket_name: "ai-core-model-checkpoints"

llm_model:
  resources:
    checkpoint: Qwen2.5-VL-7B-Instruct-AWQ