version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s | %(levelname)s | %(name)s | %(message)s"
    # Không dùng datefmt ở đây để ta set trong custom formatter Python

  access:
    class: uvicorn.logging.AccessFormatter
    format: '%(client_addr)s - "%(request_line)s" %(status_code)s'

handlers:
  default:
    class: logging.StreamHandler
    formatter: default
    stream: ext://sys.stdout

  access:
    class: logging.StreamHandler
    formatter: access
    stream: ext://sys.stdout

loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: false

  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: false

  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: false

  src:
    level: DEBUG
    handlers: [default]
    propagate: false

root:
  level: INFO
  handlers: [default]
